# Site settings
title: Hunter Dubel
description: Software Engineer
#baseurl: "/hunterdubel" # the subpath of your site, e.g. /blog
url: "hunterdubel.xyz" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hunter Dubel
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Engineer
email: hunterdubel@ieee.org
twitter_username: hdubel
github_username:  hdubel94
linkedin_username: hunter-dubel
gplus_username:  HunterDubel

# Google-analytics
google-analytics:
  id: "UA-71163561-1"

exclude: ['package.json', 'src' , 'node_modules']
