# Site settings
title: Hunter Dubel
description: DevOps Engineer | Software Engineer | Computer Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hunterdubel.xyz" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hunter Dubel
user_description: I'm always looking for new technologies to learn or ways to master my current skill set. Collector of technology with an interest in 3D printers, micro controllers, drones, and game development.
user_title: DevOps Engineer | Software Engineer | Computer Engineer
email: hunterdubel@ieee.org
twitter_username: hdubel
github_username:  hdubel94
linkedin_username: hunter-dubel
gplus_username:  HunterDubel

# Google-analytics
google-analytics:
  id: "UA-71163561-1"

exclude: ['package.json', 'src' , 'node_modules']
